FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["BlogWeb/BlogWeb.csproj", "BlogWeb/"]
RUN dotnet restore "BlogWeb/BlogWeb.csproj"
COPY BlogWeb/. BlogWeb/
WORKDIR "/src/BlogWeb"
RUN dotnet publish "BlogWeb.csproj" -c Release -o /app/publish

FROM nginx:alpine AS base
COPY nginx.conf /etc/nginx/conf.d/default.conf
RUN rm -rf /usr/share/nginx/html/*
COPY --from=build /app/publish /usr/share/nginx/html
RUN chown -R nginx:nginx /usr/share/nginx/html && chmod -R 755 /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
